Repository exoscale/terraform-provider-exoscale, pull requests merged in 2019-10, with the labels that each got.

#4 add SOS backend example
  examples/README.md
  examples/sos-backend/README.md
  examples/sos-backend/main.tf
  examples/sos-backend/variables.tf
Labels: size/S

#7 Minor fixes
  README.md
  website/docs/r/network.html.markdown
Labels: documentation, size/XS

#9 compute: replace template attribute with template_id
  examples/cloud-init/instances.tf
  examples/elastic-ip/main.tf
  examples/exokube/main.tf
  examples/import-compute/instances.tf
  examples/ipv6/main.tf
  examples/managed-private-network/main.tf
  examples/multi-private-network/instances.tf
  examples/multipart-cloud-init/instances.tf
  examples/rke/main.tf
  examples/ssh-keys/main.tf
  exoscale/datasource_exoscale_compute_template.go
  exoscale/provider_test.go
  exoscale/resource_exoscale_compute.go
  exoscale/resource_exoscale_compute_test.go
  website/docs/d/compute_template.html.markdown
  website/docs/r/compute.html.markdown
Labels: documentation, enhancement, size/L

#10 client: use DefaultPooledClient
  exoscale/client.go
  go.mod
Labels: size/XS

#12 domain_record: fix import method
  exoscale/resource_exoscale_domain_record.go
Labels: bug, size/S

#14 doc: fix remote-exec provisioner usage
  CHANGELOG.md
  examples/ssh-keys/main.tf
  website/docs/r/compute.html.markdown
Labels: documentation, size/S

#16 Add provider version to HTTP client User-Agent
  exoscale/provider.go
  version/version.go
Labels: enhancement, size/XS

#17 Set Running state if state is Migrating in compute
  exoscale/resource_exoscale_compute.go
Labels: size/XS
