Repository exoscale/terraform-provider-exoscale, pull requests merged in 2019-11, with the labels that each got.

#15 compute: reinstate "template" resource attribute
  exoscale/resource_exoscale_compute.go
  exoscale/resource_exoscale_compute_test.go
  website/docs/r/compute.html.markdown
Labels: documentation, size/XS

#20 compute: fix compute resource import
  exoscale/resource_exoscale_compute.go
Labels: bug, size/XS

#18 Add description to EIP
  examples/elastic-ip/main.tf
  exoscale/resource_exoscale_ipaddress.go
  exoscale/resource_exoscale_ipaddress_test.go
  go.mod
  go.sum
  vendor/github.com/exoscale/egoscale/.golangci.yml
  vendor/github.com/exoscale/egoscale/.gometalinter.json
  vendor/github.com/exoscale/egoscale/.travis.yml
  vendor/github.com/exoscale/egoscale/CHANGELOG.md
  vendor/github.com/exoscale/egoscale/README.md
  vendor/github.com/exoscale/egoscale/addresses.go
  vendor/github.com/exoscale/egoscale/runstatus_incident.go
  vendor/github.com/exoscale/egoscale/runstatus_maintenance.go
  vendor/github.com/exoscale/egoscale/runstatus_page.go
  vendor/github.com/exoscale/egoscale/runstatus_service.go
  vendor/github.com/exoscale/egoscale/templates.go
  vendor/github.com/exoscale/egoscale/version.go
  vendor/modules.txt
  website/docs/r/ipaddress.html.markdown
Labels: dependencies, documentation, size/M

#21 Fix cloudstack config example keyword.
  website/docs/index.html.markdown
Labels: documentation, size/XS

#23 compute: fix bug in import function
  exoscale/resource_exoscale_compute.go
Labels: bug, size/XS

#24 ipaddress: fix resource importing by IP address
  exoscale/resource_exoscale_ipaddress.go
  website/docs/r/ipaddress.html.markdown
Labels: bug, documentation, size/XS
