Repository exoscale/terraform-provider-exoscale, pull requests merged in 2019-12, with the labels that each got.

#26 Deprecate exoscale_network "network_offering" attribute
  examples/managed-private-network/main.tf
  examples/multi-private-network/networks.tf
  exoscale/provider.go
  exoscale/provider_test.go
  exoscale/resource_exoscale_network.go
  exoscale/resource_exoscale_network_test.go
  exoscale/resource_exoscale_nic_test.go
  go.mod
  go.sum
  vendor/github.com/exoscale/egoscale/CHANGELOG.md
  vendor/github.com/exoscale/egoscale/cserrorcode_string.go
  vendor/github.com/exoscale/egoscale/errorcode_string.go
  vendor/github.com/exoscale/egoscale/go.mod
  vendor/github.com/exoscale/egoscale/iam_apikey.go
  vendor/github.com/exoscale/egoscale/instance_pool.go
  vendor/github.com/exoscale/egoscale/jobstatustype_string.go
  vendor/github.com/exoscale/egoscale/network_offerings.go
  vendor/github.com/exoscale/egoscale/networkofferings_response.go
  vendor/github.com/exoscale/egoscale/networks.go
  vendor/github.com/exoscale/egoscale/record_string.go
  vendor/github.com/exoscale/egoscale/request_type.go
  vendor/github.com/exoscale/egoscale/serialization.go
  vendor/github.com/exoscale/egoscale/version.go
  vendor/modules.txt
  website/docs/r/network.html.markdown
Labels: dependencies, documentation, size/XL

#27 Replace Exoscale compute endpoint /compute by /v1
  exoscale/client.go
  exoscale/provider.go
  website/docs/index.html.markdown
Labels: documentation, size/XS

#29 Bump egoscale to v0.22.0
  go.mod
  go.sum
  vendor/github.com/exoscale/egoscale/CHANGELOG.md
  vendor/github.com/exoscale/egoscale/doc.go
  vendor/github.com/exoscale/egoscale/nics.go
  vendor/github.com/exoscale/egoscale/version.go
  vendor/modules.txt
Labels: dependencies, size/XS

#11 Add Instance pool
  examples/instance-pool/main.tf
  exoscale/provider.go
  exoscale/resource_exoscale_instance_pool.go
  exoscale/resource_exoscale_instance_pool_test.go
  go.sum
  website/docs/r/instance_pool.html.markdown
Labels: dependencies, documentation, size/XL

#32 Fix getZoneByName function
  exoscale/provider.go
  exoscale/resource_exoscale_network.go
Labels: size/M

#35 Refactor acceptance tests
  exoscale/provider_test.go
  exoscale/resource_exoscale_affinity_test.go
  exoscale/resource_exoscale_compute_test.go
  exoscale/resource_exoscale_domain_record_test.go
  exoscale/resource_exoscale_domain_test.go
  exoscale/resource_exoscale_instance_pool_test.go
  exoscale/resource_exoscale_ipaddress_test.go
  exoscale/resource_exoscale_network_test.go
  exoscale/resource_exoscale_nic_test.go
  exoscale/resource_exoscale_secondary_ipaddress_test.go
  exoscale/resource_exoscale_security_group_rule_test.go
  exoscale/resource_exoscale_security_group_rules_test.go
  exoscale/resource_exoscale_security_group_test.go
  exoscale/resource_exoscale_ssh_keypair_test.go
Labels: enhancement, size/XXL

#38 resource compute change key_pair to Optional
  exoscale/resource_exoscale_compute.go
  website/docs/r/compute.html.markdown
Labels: documentation, size/XS

#34 add domain datasource
  exoscale/datasource_exoscale_domain.go
  exoscale/datasource_exoscale_domain_test.go
  exoscale/provider.go
  website/docs/d/domain.html.markdown
Labels: documentation, size/M

#31 Add datasource on IP Address
  exoscale/datasource_exoscale_compute_ipaddress.go
  exoscale/datasource_exoscale_compute_ipaddress_test.go
  exoscale/provider.go
  website/docs/d/compute_ipaddress.html.markdown
Labels: documentation, size/XL
