Repository exoscale/terraform-provider-exoscale, pull requests merged in 2020-01, with the labels that each got.

#33 Add domain record datasource
  exoscale/datasource_exoscale_domain_record.go
  exoscale/datasource_exoscale_domain_record_test.go
  exoscale/provider.go
  go.mod
  go.sum
  website/docs/d/domain_record.html.markdown
Labels: documentation, size/XL

#39 Remove interpolation on variable attribute
  examples/cloud-init/config.tf
  examples/cloud-init/data.tf
  examples/cloud-init/instances.tf
  examples/cloud-init/security_groups.tf
  examples/cloud-init/variables.tf
  examples/dns/README.md
  examples/dns/main.tf
  examples/elastic-ip/main.tf
  examples/exokube/main.tf
  examples/exokube/output.tf
  examples/exokube/security_groups.tf
  examples/exokube/user_data.tf
  examples/import-compute/config.tf
  examples/import-compute/instances.tf
  examples/import-compute/security_groups.tf
  examples/instance-pool/main.tf
  examples/instance-pool/vars.tf
  examples/ipv6/main.tf
  examples/ipv6/variables.tf
  examples/managed-private-network/main.tf
  examples/multi-private-network/data.tf
  examples/multi-private-network/instances.tf
  examples/multi-private-network/main.tf
  examples/multi-private-network/networks.tf
  examples/multipart-cloud-init/data.tf
  examples/multipart-cloud-init/instances.tf
  examples/multipart-cloud-init/main.tf
  examples/multipart-cloud-init/outputs.tf
  examples/multipart-cloud-init/variables.tf
  examples/rke/data.tf
  examples/rke/main.tf
  examples/rke/variables.tf
  examples/s3/main.tf
  examples/sos-backend/main.tf
  examples/ssh-keys/main.tf
  exoscale/datasource_exoscale_domain_test.go
  exoscale/resource_exoscale_compute_test.go
  exoscale/resource_exoscale_domain_record_test.go
  exoscale/resource_exoscale_instance_pool_test.go
  exoscale/resource_exoscale_nic_test.go
  exoscale/resource_exoscale_security_group_rule_test.go
  exoscale/resource_exoscale_security_group_rules_test.go
  website/docs/d/compute_template.html.markdown
  website/docs/index.html.markdown
  website/docs/r/compute.html.markdown
  website/docs/r/domain_record.html.markdown
  website/docs/r/instance_pool.html.markdown
  website/docs/r/nic.html.markdown
  website/docs/r/secondary_ipaddress.html.markdown
  website/docs/r/security_group_rule.html.markdown
  website/docs/r/security_group_rules.html.markdown
Labels: documentation, size/XL

#43 doc: reference newly added resources/data sources
  website/exoscale.erb
Labels: documentation, size/XS

#44 compute: add a new "hostname" resource attribute
  exoscale/resource_exoscale_compute.go
  exoscale/resource_exoscale_compute_test.go
  website/docs/r/compute.html.markdown
Labels: documentation, size/M

#42 add compute datasource
  exoscale/datasource_exoscale_compute.go
  exoscale/datasource_exoscale_compute_test.go
  exoscale/provider.go
  website/docs/d/compute.html.markdown
  website/exoscale.erb
Labels: documentation, new-data-source, size/XL
