Repository exoscale/terraform-provider-exoscale, pull requests merged in 2020-09, with the labels that each got.

#66 healthcheck: prepare the upcoming TLS checks for managed eips
  exoscale/resource_exoscale_ipaddress.go
  exoscale/resource_exoscale_ipaddress_test.go
  go.mod
  go.sum
  vendor/github.com/exoscale/egoscale/CHANGELOG.md
  vendor/github.com/exoscale/egoscale/addresses.go
  vendor/github.com/exoscale/egoscale/version.go
  vendor/modules.txt
  website/docs/r/ipaddress.html.markdown
Labels: HOLD :hand:

#71 nlb_service: add support for HTTPS health checking
  exoscale/resource_exoscale_nlb_service.go
  exoscale/resource_exoscale_nlb_service_test.go
  go.mod
  go.sum
  vendor/github.com/exoscale/egoscale/CHANGELOG.md
  vendor/github.com/exoscale/egoscale/internal/v2/v2.gen.go
  vendor/github.com/exoscale/egoscale/loadbalancer.go
  vendor/github.com/exoscale/egoscale/version.go
  vendor/modules.txt
  website/docs/r/nlb_service.html.markdown
Labels: enhancement

#75 Improve non-existent NLB handling
  exoscale/resource_exoscale_nlb.go
Labels: bug

#74 Improve non-existent instance pool handling
  exoscale/resource_exoscale_instance_pool.go
Labels: bug

#77 Improve non-existent Private Network handling
  exoscale/resource_exoscale_network.go
Labels: bug
